# Generated by Django 3.2.24 on 2024-04-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cameratable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_no', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='logintable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='policetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('idproof', models.FileField(upload_to='')),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosurveillance_app.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='notificationtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosurveillance_app.cameratable')),
            ],
        ),
        migrations.CreateModel(
            name='feedbacktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosurveillance_app.policetable')),
            ],
        ),
        migrations.CreateModel(
            name='emergencytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('response', models.CharField(max_length=100)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosurveillance_app.policetable')),
            ],
        ),
    ]
