# Generated by Django 3.2.24 on 2024-04-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosurveillance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policetable',
            name='rank',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
